[package]
name = "libfdt-bindings"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"

[target.'cfg(target_arch="aarch64")'.dependencies]
libc = ">=0.2.39"
